/*
 * File: app/store/StEdIzm.js
 * Date: Tue Aug 11 2020 15:01:12 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ykis.store.StEdIzm', {
    extend: 'Ext.data.Store',
    alias: 'store.stEdIzm',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Number',
        'Ext.data.proxy.Memory'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'stEdIzm',
            autoLoad: true,
            data: [
                {
                    edizm: 'Гкал',
                    koef: 1
                },
                {
                    edizm: 'МВтч',
                    koef: 0.86
                },
                {
                    edizm: 'KВтч',
                    koef: 0.00086
                },
                {
                    edizm: 'ГДж',
                    koef: 0.239
                }
            ],
            fields: [
                {
                    type: 'string',
                    name: 'edizm'
                },
                {
                    type: 'float',
                    name: 'koef'
                }
            ],
            proxy: {
                type: 'memory'
            }
        }, cfg)]);
    }
});