/*
 * File: app/view/NField.js
 * Date: Mon Jun 01 2015 20:05:04 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ykis.view.NField', {
    extend: 'Ext.form.field.Number',
    alias: 'widget.nfield',

    requires: [
        'Ykis.view.NFieldViewModel',
        'Ykis.view.override.NField'
    ],

    viewModel: {
        type: 'nfield'
    },
    width: 85,
    hideLabel: true,
    value: 0,
    fieldStyle: 'background-color:#F0F8FF;font-size:11pt;text-align:right;',
    hideTrigger: true,
    autoStripChars: true

});