/*
 * File: app/view/NFTarif.js
 * Date: Tue Mar 15 2016 13:22:37 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ykis.view.NFTarif', {
    extend: 'Ext.form.field.Number',
    alias: 'widget.nftarif',

    requires: [
        'Ykis.view.override.NFTarif'
    ],

    width: 70,
    fieldLabel: 'тариф',
    labelAlign: 'top',
    labelWidth: 50,
    value: 0,
    fieldStyle: 'background-color:#F0F8FF;font-size:10pt;text-align:right;',
    hideTrigger: true,
    decimalPrecision: 3,
    step: 0.001

});