/*
 * File: app/model/MdAppartment.js
 * Date: Sat Jan 25 2020 11:53:42 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ykis.model.MdAppartment', {
    extend: 'Ext.data.Model',
    alias: 'model.mdAppartment',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Number'
    ],

    fields: [
        {
            type: 'int',
            name: 'raion_id'
        },
        {
            type: 'int',
            name: 'street_id'
        },
        {
            type: 'int',
            name: 'house_id'
        },
        {
            type: 'int',
            name: 'address_id'
        },
        {
            type: 'string',
            name: 'address'
        },
        {
            type: 'string',
            name: 'lift'
        },
        {
            type: 'int',
            name: 'room'
        },
        {
            type: 'string',
            name: 'order'
        },
        {
            type: 'date',
            name: 'data_ordera'
        },
        {
            type: 'string',
            name: 'owner'
        },
        {
            type: 'string',
            name: 'nanim'
        },
        {
            type: 'string',
            name: 'privat'
        },
        {
            type: 'int',
            name: 'tenant'
        },
        {
            type: 'int',
            name: 'absent'
        },
        {
            type: 'int',
            name: 'podnan'
        },
        {
            type: 'int',
            name: 'lgotchik'
        },
        {
            type: 'string',
            name: 'lgota'
        },
        {
            type: 'float',
            name: 'area_full'
        },
        {
            type: 'float',
            name: 'area_life'
        },
        {
            type: 'float',
            name: 'area_balk'
        },
        {
            type: 'float',
            name: 'area_dop'
        },
        {
            type: 'string',
            name: 'kvartplata'
        },
        {
            type: 'string',
            name: 'otoplenie'
        },
        {
            type: 'string',
            name: 'podogrev'
        },
        {
            type: 'string',
            name: 'voda'
        },
        {
            type: 'string',
            name: 'stoki'
        },
        {
            type: 'string',
            name: 'tbo'
        },
        {
            type: 'string',
            name: 'subsidia'
        },
        {
            type: 'string',
            name: 'vgvoda'
        },
        {
            type: 'string',
            name: 'vxvoda'
        },
        {
            type: 'string',
            name: 'teplomer'
        },
        {
            type: 'string',
            name: 'boiler'
        },
        {
            type: 'string',
            name: 'what_change'
        },
        {
            type: 'date',
            name: 'data_change'
        },
        {
            type: 'string',
            name: 'operator'
        },
        {
            type: 'string',
            name: 'floor'
        },
        {
            type: 'string',
            name: 'house'
        },
        {
            name: 'raion'
        },
        {
            type: 'string',
            name: 'street'
        },
        {
            type: 'string',
            name: 'aggr_kv'
        },
        {
            type: 'string',
            name: 'aggr_tbo'
        },
        {
            type: 'string',
            name: 'aggr_teplo'
        },
        {
            type: 'string',
            name: 'aggr_voda'
        },
        {
            type: 'float',
            name: 'tarif_ot'
        },
        {
            type: 'float',
            name: 'tarif_gv'
        },
        {
            type: 'float',
            name: 'tarif_xv'
        },
        {
            type: 'float',
            name: 'tarif_st'
        },
        {
            type: 'float',
            name: 'tarif_tbo'
        },
        {
            type: 'float',
            name: 'tarif_kv'
        },
        {
            type: 'string',
            name: 'dog_ytke'
        },
        {
            type: 'date',
            name: 'dog_ytke_data'
        },
        {
            type: 'string',
            name: 'inn'
        },
        {
            type: 'string',
            name: 'passport'
        },
        {
            type: 'string',
            name: 'vidan'
        },
        {
            type: 'date',
            name: 'viddata'
        },
        {
            type: 'int',
            name: 'dteplomer_id'
        },
        {
            type: 'int',
            name: 'teplomer_id'
        },
        {
            type: 'string',
            name: 'chdate'
        },
        {
            type: 'string',
            name: 'dog_vik'
        },
        {
            type: 'date',
            name: 'dog_vik_data'
        },
        {
            type: 'string',
            name: 'phone'
        },
        {
            type: 'float',
            name: 'area_otopl'
        },
        {
            type: 'string',
            name: 'kod'
        },
        {
            name: 'dvodomer_id'
        },
        {
            type: 'string',
            name: 'surname'
        },
        {
            type: 'string',
            name: 'surname_ua'
        },
        {
            type: 'string',
            name: 'firstname'
        },
        {
            type: 'string',
            name: 'firstname_ua'
        },
        {
            type: 'string',
            name: 'lastname'
        },
        {
            type: 'string',
            name: 'lastname_ua'
        },
        {
            type: 'string',
            name: 'rodstvo'
        },
        {
            type: 'string',
            name: 'document'
        },
        {
            type: 'string',
            name: 'seria'
        },
        {
            type: 'string',
            name: 'nomer'
        },
        {
            type: 'date',
            name: 'born'
        },
        {
            name: 'subs'
        },
        {
            type: 'string',
            name: 'vkl'
        },
        {
            type: 'date',
            name: 'datap'
        },
        {
            type: 'date',
            name: 'datav'
        },
        {
            type: 'date',
            name: 'dataprib'
        },
        {
            type: 'string',
            name: 'email'
        },
        {
            type: 'int',
            name: 'type_teplo'
        },
        {
            type: 'int',
            name: 'type_voda'
        },
        {
            type: 'int',
            name: 'cover'
        },
        {
            type: 'float',
            name: 'length'
        },
        {
            type: 'float',
            name: 'diametr'
        },
        {
            type: 'int',
            name: 'heated'
        }
    ]
});