/*
 * File: app/model/MdBanks.js
 * Date: Fri May 22 2015 20:20:12 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ykis.model.MdBanks', {
    extend: 'Ext.data.Model',
    alias: 'model.mdBanks',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer'
    ],

    idProperty: 'rec_id',

    fields: [
        {
            type: 'string',
            name: 'bank_id'
        },
        {
            type: 'string',
            name: 'fname'
        },
        {
            type: 'string',
            name: 'sname'
        },
        {
            type: 'string',
            name: 'mfo'
        },
        {
            type: 'string',
            name: 'city'
        },
        {
            type: 'string',
            name: 'np'
        },
        {
            type: 'int',
            name: 'rec_id'
        },
        {
            type: 'int',
            name: 'osn'
        },
        {
            type: 'string',
            name: 'filial_id'
        },
        {
            type: 'string',
            name: 'rs'
        },
        {
            type: 'int',
            name: 'org_id'
        },
        {
            type: 'string',
            name: 'filial'
        },
        {
            type: 'string',
            name: 'schet'
        },
        {
            type: 'string',
            name: 'what'
        }
    ]
});