/*
 * File: app/model/MdOrgPhones.js
 * Date: Mon May 25 2015 00:50:10 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ykis.model.MdOrgPhones', {
    extend: 'Ext.data.Model',
    alias: 'model.mdOrgPhones',

    requires: [
        'Ext.data.field.String'
    ],

    idProperty: 'phone_id',

    fields: [
        {
            type: 'string',
            name: 'phone_id'
        },
        {
            type: 'string',
            name: 'org_id'
        },
        {
            type: 'string',
            name: 'filial_id'
        },
        {
            type: 'string',
            name: 'phone'
        },
        {
            type: 'string',
            name: 'pname'
        },
        {
            type: 'string',
            name: 'name'
        },
        {
            type: 'string',
            name: 'what'
        }
    ]
});