/*
 * File: app/model/MdTreeOrg.js
 * Date: Sun May 10 2015 13:49:21 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ykis.model.MdTreeOrg', {
    extend: 'Ext.data.Model',
    alias: 'model.mdTreeOrg',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Integer'
    ],

    fields: [
        {
            type: 'string',
            name: 'id'
        },
        {
            type: 'int',
            name: 'org_id'
        },
        {
            type: 'int',
            name: 'orig_id'
        },
        {
            type: 'string',
            name: 'name'
        },
        {
            type: 'string',
            name: 'fname'
        },
        {
            type: 'string',
            name: 'sname'
        },
        {
            type: 'string',
            name: 'text'
        },
        {
            type: 'string',
            name: 'abbr'
        },
        {
            type: 'string',
            name: 'what'
        },
        {
            type: 'int',
            name: 'cat_id'
        },
        {
            type: 'int',
            name: 'golovnoe'
        },
        {
            type: 'int',
            name: 'ind'
        }
    ]
});