/*
 * File: app/view/flat/TabKassaViewController.js
 * Date: Sat May 23 2020 13:41:59 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ykis.view.flat.TabKassaViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.tabkassa',

    onCbDo1Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var zadol = form.getForm().findField('zadol1').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var dolg = form.getForm().findField('dolg1').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);


        if (newValue) {
            if(zadol >  0 && dolg >= 1){
                form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+zadol)).focus();
                form.getForm().findField('cbNext1').setDisabled(true);
                form.getForm().findField('zadol1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('period1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('nachisleno1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('budjet1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplacheno1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('subsidia1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('dolg1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('cbDo1').setValue(false);
            }
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-zadol)).focus();
            form.getForm().findField('cbNext1').setDisabled(false);
            form.getForm().findField('zadol1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg1').setFieldStyle('background-color: #F0F8FF; background-image: none;');

        }
    },

    onCbDo2Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var zadol = form.getForm().findField('zadol2').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var dolg = form.getForm().findField('dolg2').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);

        if (newValue) {
            if(zadol >  0 && dolg >= 1 ){
                form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+zadol)).focus();
                form.getForm().findField('cbNext2').setDisabled(true);
                form.getForm().findField('zadol2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('period2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('nachisleno2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('budjet2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplacheno2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('subsidia2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('dolg2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('cbDo2').setValue(false);
            }
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-zadol)).focus();
            form.getForm().findField('cbNext2').setDisabled(false);
            form.getForm().findField('zadol2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg2').setFieldStyle('background-color: #F0F8FF; background-image: none;');

        }
    },

    onCbDo3Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var zadol = form.getForm().findField('zadol3').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var dolg = form.getForm().findField('dolg3').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);

        if (newValue) {
            if(zadol >  0 && dolg >= 1){
                form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+zadol)).focus();
                form.getForm().findField('cbNext3').setDisabled(true);
                form.getForm().findField('zadol3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('period3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('nachisleno3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('budjet3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplacheno3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('subsidia3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('dolg3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('cbDo3').setValue(false);
            }
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-zadol)).focus();
            form.getForm().findField('cbNext3').setDisabled(false);
            form.getForm().findField('zadol3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg3').setFieldStyle('background-color: #F0F8FF; background-image: none;');

        }
    },

    onCbDo8Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var zadol = form.getForm().findField('zadol8').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var dolg = form.getForm().findField('dolg8').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);

        if (newValue) {
            if(zadol >  0 && dolg >= 1){
                form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+zadol)).focus();
                form.getForm().findField('cbNext8').setDisabled(true);
                form.getForm().findField('zadol8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('period8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('nachisleno8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('budjet8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplacheno8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('subsidia8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('dolg8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('cbDo3').setValue(false);
            }
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-zadol)).focus();
            form.getForm().findField('cbNext8').setDisabled(false);
            form.getForm().findField('zadol8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg8').setFieldStyle('background-color: #F0F8FF; background-image: none;');

        }
    },

    onCbDo4Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var zadol = form.getForm().findField('zadol4').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var dolg = form.getForm().findField('dolg4').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);

        if (newValue) {
            if(zadol >  0 && dolg >= 1){
                form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+zadol)).focus();
                form.getForm().findField('cbNext4').setDisabled(true);
                form.getForm().findField('zadol4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('period4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('nachisleno4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('budjet4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplacheno4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('subsidia4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('dolg4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('cbDo4').setValue(false);
            }
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-zadol)).focus();
            form.getForm().findField('cbNext4').setDisabled(false);
            form.getForm().findField('zadol4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg4').setFieldStyle('background-color: #F0F8FF; background-image: none;');

        }
    },

    onCbDo5Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var zadol = form.getForm().findField('zadol5').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var dolg = form.getForm().findField('dolg5').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);

        if (newValue) {
            if(zadol >  0 && dolg >= 1){
                form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+zadol)).focus();
                form.getForm().findField('cbNext5').setDisabled(true);
                form.getForm().findField('zadol5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('period5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('nachisleno5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('budjet5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplacheno5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('subsidia5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('dolg5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('cbDo5').setValue(false);
            }
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-zadol)).focus();
            form.getForm().findField('cbNext5').setDisabled(false);
            form.getForm().findField('zadol5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg5').setFieldStyle('background-color: #F0F8FF; background-image: none;');

        }
    },

    onCbDo6Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var zadol = form.getForm().findField('zadol6').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var dolg = form.getForm().findField('dolg6').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);

        if (newValue) {
            if(zadol >  0 && dolg >= 1){
                form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+zadol)).focus();
                form.getForm().findField('cbNext6').setDisabled(true);
                form.getForm().findField('zadol6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('period6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('nachisleno6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('budjet6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplacheno6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('subsidia6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('dolg6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('cbDo6').setValue(false);
            }
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-zadol)).focus();
            form.getForm().findField('cbNext6').setDisabled(false);
            form.getForm().findField('zadol6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
    },

    onCbDo6Change1: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var zadol = form.getForm().findField('zadol7').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        var dolg = form.getForm().findField('dolg7').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);

        if (newValue) {
            if(zadol >  0 && dolg >= 1){
                form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+zadol)).focus();
                form.getForm().findField('cbNext7').setDisabled(true);
                form.getForm().findField('zadol7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('period7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('nachisleno7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('budjet7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('oplacheno7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('subsidia7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
                form.getForm().findField('dolg7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            }else {
                form.getForm().findField('cbDo7').setValue(false);
            }
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-zadol)).focus();
            form.getForm().findField('cbNext7').setDisabled(false);
            form.getForm().findField('zadol7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
    },

    onDoAllClick: function(button, e, eOpts) {
        var form = button.findParentByType('form');
        var zadol = 0;
        var zadol1 = form.getForm().findField('zadol1').getValue();
        var zadol2 = form.getForm().findField('zadol2').getValue();
        var zadol3 = form.getForm().findField('zadol3').getValue();
        var zadol4 = form.getForm().findField('zadol4').getValue();
        var zadol5 = form.getForm().findField('zadol5').getValue();
        var zadol6 = form.getForm().findField('zadol6').getValue();
        var zadol7 = form.getForm().findField('zadol7').getValue();
        var zadol8 = form.getForm().findField('zadol8').getValue();


        var dolg1 = form.getForm().findField('dolg1').getValue();
        var dolg2 = form.getForm().findField('dolg2').getValue();
        var dolg3 = form.getForm().findField('dolg3').getValue();
        var dolg4 = form.getForm().findField('dolg4').getValue();
        var dolg5 = form.getForm().findField('dolg5').getValue();
        var dolg6 = form.getForm().findField('dolg7').getValue();
        var dolg7 = form.getForm().findField('dolg7').getValue();
        var dolg8 = form.getForm().findField('dolg8').getValue();


        if(zadol1 > 0 && dolg1 >= 1){
            zadol +=zadol1;
            form.getForm().findField('cbDo1').setValue(true);
            form.getForm().findField('cbNext1').setValue(false);
            form.getForm().findField('cbNext1').setDisabled(true);
            form.getForm().findField('zadol1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        } else {
            form.getForm().findField('cbDo1').setValue(false);
            form.getForm().findField('cbNext1').setValue(false);
            form.getForm().findField('cbNext1').setDisabled(true);
            form.getForm().findField('zadol1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(zadol2 > 0 && dolg2 >= 1){
            zadol +=zadol2;
            form.getForm().findField('cbDo2').setValue(true);
            form.getForm().findField('cbNext2').setValue(false);
            form.getForm().findField('cbNext2').setDisabled(true);
            form.getForm().findField('zadol2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg2').setFieldStyle('background-color: #FAFAD2; background-image: none;');

        } else {
            form.getForm().findField('cbDo2').setValue(false);
            form.getForm().findField('cbNext2').setValue(false);
            form.getForm().findField('cbNext2').setDisabled(true);
            form.getForm().findField('zadol2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(zadol3 > 0 && dolg3 >= 1){
            zadol +=zadol3;
            form.getForm().findField('cbDo3').setValue(true);
            form.getForm().findField('cbNext3').setValue(false);
            form.getForm().findField('cbNext3').setDisabled(true);
            form.getForm().findField('zadol3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        } else {
            form.getForm().findField('cbDo3').setValue(false);
            form.getForm().findField('cbNext3').setValue(false);
            form.getForm().findField('cbNext3').setDisabled(true);
            form.getForm().findField('zadol3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(zadol4 > 0 && dolg4 >= 1){
            zadol +=zadol4;
            form.getForm().findField('cbDo4').setValue(true);
            form.getForm().findField('cbNext4').setValue(false);
            form.getForm().findField('cbNext4').setDisabled(true);
            form.getForm().findField('zadol4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        } else {
            form.getForm().findField('cbDo4').setValue(false);
            form.getForm().findField('cbNext4').setValue(false);
            form.getForm().findField('cbNext4').setDisabled(true);
            form.getForm().findField('zadol4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(zadol5 > 0 && dolg5 >=1){
            zadol +=zadol5;
            form.getForm().findField('cbDo5').setValue(true);
            form.getForm().findField('cbNext5').setValue(false);
            form.getForm().findField('cbNext5').setDisabled(true);
            form.getForm().findField('zadol5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        } else {
            form.getForm().findField('cbDo5').setValue(false);
            form.getForm().findField('cbNext5').setValue(false);
            form.getForm().findField('cbNext5').setDisabled(true);
            form.getForm().findField('zadol5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(zadol7 > 0 && dolg6 >= 1){
            zadol +=zadol6;
            form.getForm().findField('cbDo6').setValue(true);
            form.getForm().findField('cbNext6').setValue(false);
            form.getForm().findField('cbNext6').setDisabled(true);
            form.getForm().findField('zadol6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs6').setFieldStyle('background-color: #FAFAD2; background-image: none;');

            form.getForm().findField('dolg6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        } else {
            form.getForm().findField('cbDo6').setValue(false);
            form.getForm().findField('cbNext6').setValue(false);
            form.getForm().findField('cbNext6').setDisabled(true);
            form.getForm().findField('zadol6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(zadol7 > 0 && dolg7 >= 1){
            zadol +=zadol7;
            form.getForm().findField('cbDo7').setValue(true);
            form.getForm().findField('cbNext7').setValue(false);
            form.getForm().findField('cbNext7').setDisabled(true);
            form.getForm().findField('zadol7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        } else {
            form.getForm().findField('cbDo7').setValue(false);
            form.getForm().findField('cbNext7').setValue(false);
            form.getForm().findField('cbNext7').setDisabled(true);
            form.getForm().findField('zadol7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(zadol8 > 0 && dolg8 >= 1){
            zadol +=zadol8;
            form.getForm().findField('cbDo8').setValue(true);
            form.getForm().findField('cbNext8').setValue(false);
            form.getForm().findField('cbNext8').setDisabled(true);
            form.getForm().findField('zadol8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        } else {
            form.getForm().findField('cbDo8').setValue(false);
            form.getForm().findField('cbNext8').setValue(false);
            form.getForm().findField('cbNext8').setDisabled(true);
            form.getForm().findField('zadol8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(zadol >=0.01 ){

            form.down('#NextAll').setDisabled(true);
            form.down('#NextAllReset').setDisabled(false);
            form.down('#DoAllReset').setDisabled(false);
            form.getForm().findField('newOplata').setDisabled(false);
            form.getForm().findField('newOplata').setValue(Math.round(zadol)).focus();
        } else {

        }

    },

    onNextAllClick: function(button, e, eOpts) {
        var form = button.findParentByType('form');
        var dolg = 0;
        var dolg1 = form.getForm().findField('dolg1').getValue();
        var dolg2 = form.getForm().findField('dolg2').getValue();
        var dolg3 = form.getForm().findField('dolg3').getValue();
        var dolg4 = form.getForm().findField('dolg4').getValue();
        var dolg5 = form.getForm().findField('dolg5').getValue();
        var dolg6 = form.getForm().findField('dolg6').getValue();
        var dolg7 = form.getForm().findField('dolg7').getValue();
        var dolg8 = form.getForm().findField('dolg8').getValue();


        if(dolg1 > 0){
            dolg +=dolg1;
            form.getForm().findField('cbNext1').setValue(true);
            form.getForm().findField('cbDo1').setValue(false);
            form.getForm().findField('cbDo1').setDisabled(true);
            form.getForm().findField('zadol1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        } else {
            form.getForm().findField('cbNext1').setValue(false);
            form.getForm().findField('cbDo1').setValue(false);
            form.getForm().findField('cbDo1').setDisabled(true);
            form.getForm().findField('zadol1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(dolg2 > 0){
            dolg +=dolg2;
            form.getForm().findField('cbNext2').setValue(true);
            form.getForm().findField('cbDo2').setValue(false);
            form.getForm().findField('cbDo2').setDisabled(true);
            form.getForm().findField('zadol2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg2').setFieldStyle('background-color: #FAFAD2; background-image: none;');

        } else {
            form.getForm().findField('cbNext2').setValue(false);
            form.getForm().findField('cbDo2').setValue(false);
            form.getForm().findField('cbDo2').setDisabled(true);
            form.getForm().findField('zadol2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(dolg3 > 0){
            dolg +=dolg3;
            form.getForm().findField('cbNext3').setValue(true);
            form.getForm().findField('cbDo3').setValue(false);
            form.getForm().findField('cbDo3').setDisabled(true);
            form.getForm().findField('zadol3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        } else {
            form.getForm().findField('cbNext3').setValue(false);
            form.getForm().findField('cbDo3').setValue(false);
            form.getForm().findField('cbDo3').setDisabled(true);
            form.getForm().findField('zadol3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(dolg4 > 0){
            dolg +=dolg4;
            form.getForm().findField('cbNext4').setValue(true);
            form.getForm().findField('cbDo4').setValue(false);
            form.getForm().findField('cbDo4').setDisabled(true);
            form.getForm().findField('zadol4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        } else {
            form.getForm().findField('cbNext4').setValue(false);
            form.getForm().findField('cbDo4').setValue(false);
            form.getForm().findField('cbDo4').setDisabled(true);
            form.getForm().findField('zadol4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(dolg5 > 0){
            dolg +=dolg5;
            form.getForm().findField('cbNext5').setValue(true);
            form.getForm().findField('cbDo5').setValue(false);
            form.getForm().findField('cbDo5').setDisabled(true);
            form.getForm().findField('zadol5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        } else {
            form.getForm().findField('cbNext5').setValue(false);
            form.getForm().findField('cbDo5').setValue(false);
            form.getForm().findField('cbDo5').setDisabled(true);
            form.getForm().findField('zadol5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(dolg6 > 0){
            dolg +=dolg6;
            form.getForm().findField('cbNext6').setValue(true);
            form.getForm().findField('cbDo6').setValue(false);
            form.getForm().findField('cbDo6').setDisabled(true);
            form.getForm().findField('zadol6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        } else {
            form.getForm().findField('cbNext6').setValue(false);
            form.getForm().findField('cbDo6').setValue(false);
            form.getForm().findField('cbDo6').setDisabled(true);
            form.getForm().findField('zadol6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(dolg7 > 0){
            dolg +=dolg7;
            form.getForm().findField('cbNext7').setValue(true);
            form.getForm().findField('cbDo7').setValue(false);
            form.getForm().findField('cbDo7').setDisabled(true);
            form.getForm().findField('zadol7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        } else {
            form.getForm().findField('cbNext7').setValue(false);
            form.getForm().findField('cbDo7').setValue(false);
            form.getForm().findField('cbDo7').setDisabled(true);
            form.getForm().findField('zadol7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(dolg8 > 0){
            dolg +=dolg8;
            form.getForm().findField('cbNext8').setValue(true);
            form.getForm().findField('cbDo8').setValue(false);
            form.getForm().findField('cbDo8').setDisabled(true);
            form.getForm().findField('zadol8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subs8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        } else {
            form.getForm().findField('cbNext8').setValue(false);
            form.getForm().findField('cbDo8').setValue(false);
            form.getForm().findField('cbDo8').setDisabled(true);
            form.getForm().findField('zadol8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subs8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
        if(dolg >=0.01 ){

            form.getForm().findField('newOplata').setDisabled(false);
            form.getForm().findField('newOplata').setValue(Math.round(dolg)).focus();
            form.down('#DoAll').setDisabled(true);
            form.down('#NextAllReset').setDisabled(false);
            form.down('#DoAllReset').setDisabled(false);
        } else {
            form.getForm().findField('newOplata').setDisabled(false);
            form.getForm().findField('newOplata').setValue(0).focus();
        }

    },

    onCbNext1Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg1').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);

        if (newValue) {
            form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+dolg)).focus();
            form.getForm().findField('cbDo1').setDisabled(true);
            form.getForm().findField('zadol1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg1').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-dolg)).focus();
            form.getForm().findField('cbDo1').setDisabled(false);
            form.getForm().findField('zadol1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia1').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg1').setFieldStyle('background-color: #F0F8FF; background-image: none;');

        }
    },

    onCbNext2Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg2').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);

        if (newValue) {
            form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+dolg)).focus();
            form.getForm().findField('cbDo2').setDisabled(true);
            form.getForm().findField('zadol2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg2').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-dolg)).focus();
            form.getForm().findField('cbDo2').setDisabled(false);
            form.getForm().findField('zadol2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia2').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg2').setFieldStyle('background-color: #F0F8FF; background-image: none;');

        }
    },

    onCbNext3Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg3').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);

        if (newValue) {
            form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+dolg)).focus();
            form.getForm().findField('cbDo3').setDisabled(true);
            form.getForm().findField('zadol3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg3').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-dolg)).focus();
            form.getForm().findField('cbDo3').setDisabled(false);
            form.getForm().findField('zadol3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia3').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg3').setFieldStyle('background-color: #F0F8FF; background-image: none;');

        }
    },

    onCbNext8Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg8').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);

        if (newValue) {
            form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+dolg)).focus();
            form.getForm().findField('cbDo8').setDisabled(true);
            form.getForm().findField('zadol8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg8').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-dolg)).focus();
            form.getForm().findField('cbDo8').setDisabled(false);
            form.getForm().findField('zadol8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia8').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg8').setFieldStyle('background-color: #F0F8FF; background-image: none;');

        }
    },

    onCbNext4Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg4').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);

        if (newValue) {
            form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+dolg)).focus();
            form.getForm().findField('cbDo4').setDisabled(true);
            form.getForm().findField('zadol4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg4').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-dolg)).focus();
            form.getForm().findField('cbDo4').setDisabled(false);
            form.getForm().findField('zadol4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia4').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg4').setFieldStyle('background-color: #F0F8FF; background-image: none;');


        }
    },

    onCbNext5Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg5').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);

        if (newValue) {

            form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+dolg)).focus();
            form.getForm().findField('cbDo5').setDisabled(true);
            form.getForm().findField('zadol5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg5').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-dolg)).focus();
            form.getForm().findField('cbDo5').setDisabled(false);
            form.getForm().findField('zadol5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia5').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg5').setFieldStyle('background-color: #F0F8FF; background-image: none;');

        }
    },

    onCbNext6Change: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg6').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);

        if (newValue) {
            form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+dolg)).focus();
            form.getForm().findField('cbDo6').setDisabled(true);
            form.getForm().findField('zadol6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg6').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-dolg)).focus();
            form.getForm().findField('cbDo6').setDisabled(false);
            form.getForm().findField('zadol6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg6').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
    },

    onCbNext6Change1: function(field, newValue, oldValue, eOpts) {
        var form = field.findParentByType('form');
        var dolg = form.getForm().findField('dolg7').getValue();
        var value = form.getForm().findField('newOplata').getValue();
        form.down('#DoAllReset').setDisabled(false);
        form.down('#NextAllReset').setDisabled(false);

        if (newValue) {
            form.getForm().findField('newOplata').setDisabled(false).setValue(Math.round(value+dolg)).focus();
            form.getForm().findField('cbDo7').setDisabled(true);
            form.getForm().findField('zadol7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('period7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('nachisleno7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('budjet7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('oplacheno7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('subsidia7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
            form.getForm().findField('dolg7').setFieldStyle('background-color: #FAFAD2; background-image: none;');
        }else {
            form.getForm().findField('newOplata').setValue(Math.round(value-dolg)).focus();
            form.getForm().findField('cbDo7').setDisabled(false);
            form.getForm().findField('zadol7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('period7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('nachisleno7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('budjet7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('oplacheno7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('subsidia7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
            form.getForm().findField('dolg7').setFieldStyle('background-color: #F0F8FF; background-image: none;');
        }
    },

    onNewOplataKassaValidityChange: function(field, isValid, eOpts) {
        var form = field.findParentByType('form');
        if(isValid){
            form.down('#insTekPokKassa').setDisabled(false);
        } else {
            form.down('#insTekPokKassa').setDisabled(true);
        }
    }

});
