/*
 * File: app/view/flat/TabNachAppTeploViewController.js
 * Date: Sat Mar 28 2020 02:33:16 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ykis.view.flat.TabNachAppTeploViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.tabnachappteplo',

    onDatefieldSelectPerer: function(field, value, eOpts) {
        var form = field.findParentByType('form').getForm();

        var StTekNachApp = Ext.data.StoreManager.get("StTekNachApp");

        StTekNachApp.each(function(record){
            if(Ext.Date.format(record.get('data'), 'F,Y') == Ext.Date.format(value, 'F,Y')) {
                form.findField('tarif_perer').setValue(record.get('tarif_gkal'));
                form.findField('gkal_old').setValue(record.get('gkal'));


                // console.log(Ext.Date.format(record.get('data'), 'F,Y'));
            }

        });

    }

});
