/*
 * File: app/view/flat/WinFamaly.js
 * Date: Sun May 17 2020 02:44:16 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ykis.view.flat.WinFamaly', {
    extend: 'Ext.window.Window',
    alias: 'widget.winfamaly',

    requires: [
        'Ykis.view.flat.WinFamalyViewModel',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.field.Checkbox',
        'Ext.form.field.Hidden',
        'Ext.form.field.Number'
    ],

    viewModel: {
        type: 'winfamaly'
    },
    height: 493,
    id: 'winFamaly',
    width: 679,
    layout: 'fit',
    title: 'Додавання квартіросьемщіка',
    modal: true,
    defaultListenerScope: true,

    items: [
        {
            xtype: 'form',
            id: 'fmFamaly',
            layout: 'absolute',
            bodyPadding: 10,
            title: '',
            paramsAsHash: true,
            items: [
                {
                    xtype: 'fieldset',
                    x: 25,
                    y: 230,
                    height: 160,
                    padding: '10 10 10 10',
                    style: 'background-color: #DCDCDC;',
                    width: 625,
                    layout: 'absolute',
                    title: 'Статутні документи',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 5,
                            y: 5,
                            formBind: false,
                            width: 190,
                            fieldLabel: 'Інн',
                            labelWidth: 60,
                            name: 'inn',
                            allowBlank: false,
                            maxLength: 12,
                            maxLengthText: 'Максимальная длина для этого поля 12 символов'
                        },
                        {
                            xtype: 'textfield',
                            x: 5,
                            y: 85,
                            formBind: false,
                            width: 585,
                            fieldLabel: 'Выдан',
                            labelWidth: 60,
                            name: 'organ',
                            maxLengthText: 'Максимальная длина для этого поля 12 символов'
                        },
                        {
                            xtype: 'textfield',
                            x: 5,
                            y: 45,
                            formBind: false,
                            width: 140,
                            fieldLabel: 'серія',
                            labelWidth: 60,
                            name: 'seria',
                            maxLengthText: 'Максимальная длина для этого поля 12 символов'
                        },
                        {
                            xtype: 'textfield',
                            x: 185,
                            y: 45,
                            formBind: false,
                            width: 160,
                            fieldLabel: 'номер',
                            labelWidth: 60,
                            name: 'nomer',
                            maxLengthText: 'Максимальная длина для этого поля 12 символов'
                        },
                        {
                            xtype: 'datefield',
                            x: 365,
                            y: 45,
                            width: 225,
                            fieldLabel: 'дата видачі',
                            labelWidth: 90,
                            name: 'datapasp',
                            format: 'd-m-Y',
                            submitFormat: 'Y-m-d'
                        },
                        {
                            xtype: 'combobox',
                            x: 235,
                            y: 5,
                            width: 355,
                            fieldLabel: 'Документ',
                            labelWidth: 80,
                            name: 'document',
                            allowBlank: false,
                            anyMatch: true,
                            displayField: 'document',
                            queryMode: 'local',
                            store: 'StDocument',
                            valueField: 'document'
                        }
                    ]
                },
                {
                    xtype: 'button',
                    handler: function(button, event) {
                        this.up('#winFamaly').close();
                    },
                    x: 25,
                    y: 400,
                    formBind: false,
                    height: 30,
                    width: 115,
                    icon: 'resources/css/images/ico/delete.png',
                    text: 'Відміна'
                },
                {
                    xtype: 'fieldset',
                    x: 25,
                    y: 55,
                    height: 165,
                    style: 'background-color: #DCDCDC;',
                    width: 625,
                    layout: 'absolute',
                    title: 'квартіросьемщік',
                    items: [
                        {
                            xtype: 'textfield',
                            x: 5,
                            y: 40,
                            width: 250,
                            fieldLabel: 'Прізвище',
                            labelWidth: 80,
                            name: 'surname',
                            allowBlank: false,
                            maxLengthText: 'Максимальная длина для этого поля 8 символов'
                        },
                        {
                            xtype: 'textfield',
                            x: 5,
                            y: 110,
                            width: 250,
                            fieldLabel: 'Побатькові',
                            labelWidth: 80,
                            name: 'lastname',
                            allowBlank: false,
                            maxLengthText: 'Максимальная длина для этого поля 8 символов'
                        },
                        {
                            xtype: 'textfield',
                            x: 5,
                            y: 75,
                            width: 250,
                            fieldLabel: 'Им’я',
                            labelWidth: 80,
                            name: 'firstname',
                            allowBlank: false,
                            maxLengthText: 'Максимальная длина для этого поля 8 символов'
                        },
                        {
                            xtype: 'datefield',
                            x: 25,
                            y: 5,
                            width: 245,
                            fieldLabel: 'дата реєстрації',
                            labelWidth: 120,
                            name: 'datap',
                            format: 'd-m-Y',
                            submitFormat: 'Y-m-d'
                        },
                        {
                            xtype: 'datefield',
                            x: 340,
                            y: 40,
                            width: 245,
                            fieldLabel: 'дата народження',
                            labelWidth: 120,
                            name: 'born',
                            format: 'd-m-Y',
                            submitFormat: 'Y-m-d'
                        },
                        {
                            xtype: 'combobox',
                            x: 280,
                            y: 75,
                            width: 305,
                            fieldLabel: 'Родство',
                            labelWidth: 80,
                            name: 'rodstvo',
                            allowBlank: false,
                            anyMatch: true,
                            displayField: 'rodstvo',
                            queryMode: 'local',
                            store: 'StRodstvo',
                            valueField: 'rodstvo'
                        },
                        {
                            xtype: 'checkboxfield',
                            x: 265,
                            y: 110,
                            width: 200,
                            fieldLabel: 'Пользуется субсидией',
                            labelWidth: 150,
                            name: 'subsidia',
                            inputValue: 'да',
                            uncheckedValue: 'нет',
                            listeners: {
                                change: 'onCheckboxfieldChange'
                            }
                        },
                        {
                            xtype: 'checkboxfield',
                            x: 475,
                            y: 110,
                            width: 125,
                            fieldLabel: 'Отсутствует',
                            labelWidth: 85,
                            name: 'absent',
                            inputValue: '1',
                            uncheckedValue: '0',
                            listeners: {
                                change: 'onCheckboxfieldChange1'
                            }
                        },
                        {
                            xtype: 'checkboxfield',
                            x: 330,
                            y: 5,
                            width: 50,
                            fieldLabel: 'Включений до складу сім\'ї',
                            labelWidth: 180,
                            name: 'vkl',
                            boxLabel: 'Вкл',
                            checked: true,
                            inputValue: 'да',
                            uncheckedValue: 'нет',
                            listeners: {
                                change: 'onCheckboxfieldChange'
                            }
                        }
                    ]
                },
                {
                    xtype: 'button',
                    x: 285,
                    y: 400,
                    formBind: true,
                    height: 30,
                    id: 'winBtnAddCitizen',
                    width: 365,
                    icon: 'resources/css/images/ico/add.png',
                    text: 'Додати квартіросьемщіка'
                },
                {
                    xtype: 'hiddenfield',
                    fieldLabel: 'Label',
                    name: 'rec_id'
                },
                {
                    xtype: 'numberfield',
                    x: 40,
                    y: 20,
                    width: 190,
                    fieldLabel: 'код квартири',
                    name: 'address_id',
                    hideTrigger: true
                }
            ]
        }
    ],

    onCheckboxfieldChange: function(field, newValue, oldValue, eOpts) {
        if(newValue){
            field.setBoxLabel("Вкл");
        }else{
            field.setBoxLabel("Откл");
        }
    },

    onCheckboxfieldChange1: function(field, newValue, oldValue, eOpts) {
        if(newValue){
            field.setBoxLabel("да");
        }else{
            field.setBoxLabel("нет");
        }
    },

    onCheckboxfieldChange: function(field, newValue, oldValue, eOpts) {
        if(newValue){
            field.setBoxLabel("Вкл");
        }else{
            field.setBoxLabel("Откл");
        }
    }

});