/*
 * File: app/view/sprav/TabKvartplata.js
 * Date: Tue May 12 2020 01:39:10 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ykis.view.sprav.TabKvartplata', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tabkvartplata',

    requires: [
        'Ykis.view.sprav.TabKvartplataViewModel',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.button.Button',
        'Ext.form.FieldSet',
        'Ext.form.field.Checkbox',
        'Ext.form.field.ComboBox',
        'Ext.form.field.Number',
        'Ext.form.field.Hidden',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.selection.CheckboxModel',
        'Ext.grid.column.Number'
    ],

    viewModel: {
        type: 'tabkvartplata'
    },
    id: 'tabKvartplata',
    scrollable: true,
    layout: 'fit',
    bodyBorder: false,
    closable: true,
    title: 'Начисление квартплаты',
    defaultListenerScope: true,

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    {
                        xtype: 'form',
                        height: 705,
                        id: 'fmKvartplata',
                        scrollable: true,
                        layout: 'absolute',
                        bodyPadding: 10,
                        title: '',
                        items: [
                            {
                                xtype: 'datefield',
                                x: 15,
                                y: 25,
                                style: 'background-color: #e0e0e0;',
                                width: 280,
                                fieldLabel: 'Период начисления',
                                labelWidth: 130,
                                name: 'data',
                                format: 'F,Y',
                                startDay: 1,
                                submitFormat: 'Ymd',
                                listeners: {
                                    select: 'onDatefieldSelect'
                                }
                            },
                            {
                                xtype: 'button',
                                x: 325,
                                y: 25,
                                formBind: false,
                                height: 30,
                                id: 'btAddNachKv',
                                width: 510,
                                icon: 'resources/css/images/ico/yes.png',
                                text: 'начислить квартплату'
                            },
                            {
                                xtype: 'panel',
                                x: 10,
                                y: 70,
                                height: 325,
                                id: 'pnPererKv',
                                width: 905,
                                layout: 'absolute',
                                title: 'Перерасчет по',
                                items: [
                                    {
                                        xtype: 'fieldset',
                                        x: 0,
                                        y: 10,
                                        height: 85,
                                        style: 'background-color: #e0e0e0;',
                                        width: 190,
                                        title: 'Период перерасчета',
                                        items: [
                                            {
                                                xtype: 'datefield',
                                                anchor: '100%',
                                                width: 185,
                                                fieldLabel: 'Дата с',
                                                labelWidth: 60,
                                                name: 'sdata',
                                                format: 'd-m-Y',
                                                submitFormat: 'Ymd'
                                            },
                                            {
                                                xtype: 'datefield',
                                                anchor: '100%',
                                                width: 185,
                                                fieldLabel: 'Дата по',
                                                labelWidth: 60,
                                                name: 'fdata',
                                                format: 'd-m-Y',
                                                submitFormat: 'Ymd'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        x: 195,
                                        y: 10,
                                        height: 85,
                                        style: 'background-color: #e0e0e0;',
                                        width: 705,
                                        layout: 'absolute',
                                        title: 'Ограничение по адресам',
                                        items: [
                                            {
                                                xtype: 'checkboxfield',
                                                handler: function(checkbox, checked) {
                                                    var form = checkbox.findParentByType('form');
                                                    var  address_ot = form.getForm().findField('address_ot');
                                                    var  address_do = form.getForm().findField('address_do');
                                                    var  printRaspechatkaHouseMgkc = Ext.getCmp('printRaspechatkaHouseMgkc');


                                                    if(checked===true){
                                                        if (address_ot.isVisible()) address_ot.hide();
                                                        if (address_do.isVisible()) address_do.hide();
                                                        if (printRaspechatkaHouseMgkc.isVisible()) printRaspechatkaHouseMgkc.hide();
                                                    } else {
                                                        if (address_ot.isHidden()) address_ot.show();
                                                        if (address_do.isHidden()) address_do.show();
                                                        if (printRaspechatkaHouseMgkc.isHidden()) printRaspechatkaHouseMgkc.show();



                                                    }
                                                },
                                                x: 0,
                                                y: 0,
                                                hidden: true,
                                                style: 'background-color: #C2D9E9;',
                                                fieldLabel: 'По всем квартирам дома',
                                                labelWidth: 160,
                                                name: 'allkv',
                                                boxLabel: '',
                                                checked: true,
                                                inputValue: '1',
                                                uncheckedValue: '0'
                                            },
                                            {
                                                xtype: 'combobox',
                                                x: 195,
                                                y: 0,
                                                hidden: true,
                                                width: 185,
                                                fieldLabel: 'c',
                                                labelWidth: 20,
                                                name: 'address_ot',
                                                enableKeyEvents: true,
                                                displayField: 'address',
                                                forceSelection: true,
                                                queryMode: 'local',
                                                store: 'StAddressOrg',
                                                valueField: 'address_id'
                                            },
                                            {
                                                xtype: 'combobox',
                                                x: 195,
                                                y: 30,
                                                hidden: true,
                                                width: 185,
                                                fieldLabel: 'по',
                                                labelWidth: 20,
                                                name: 'address_do',
                                                editable: false,
                                                displayField: 'address',
                                                forceSelection: true,
                                                queryMode: 'local',
                                                store: 'StAddressOrg',
                                                valueField: 'address_id'
                                            },
                                            {
                                                xtype: 'button',
                                                x: 405,
                                                y: 10,
                                                formBind: true,
                                                height: 30,
                                                id: 'btAddPererKv',
                                                width: 195,
                                                icon: 'resources/css/images/ico/yes.png',
                                                text: 'Перерасчитать квартплату'
                                            },
                                            {
                                                xtype: 'button',
                                                handler: function(button, event) {
                                                    var value = button.findParentByType('form').getValues();
                                                    var StUser = Ext.data.StoreManager.get("StUser");
                                                    var StReport = Ext.data.StoreManager.get("StReport");
                                                    var values =StUser.getAt(0);

                                                    //console.log(value);

                                                    var usertype = 1;

                                                    var tabPnCenter =  Ext.getCmp('tabPnCenter');//me.getTabPnCenter();



                                                    if (value.house_id !==0) {

                                                        var report = 'HouseKvRaspechatkaMgkc';
                                                        var namereport = 'Распечатка дома';

                                                        var params = {
                                                            login:values.get('login'),
                                                            password:values.get('password'),
                                                            report:report,
                                                            what:report
                                                        };

                                                        var tab = tabPnCenter.child('#'+report);

                                                        if (!tab) {
                                                            tab  = tabPnCenter.add({
                                                                xtype:'tabreportorg',
                                                                title:namereport,
                                                                id:''+report+''
                                                            });

                                                            tabPnCenter.setActiveTab(tab);

                                                        }else{

                                                            tabPnCenter.setActiveTab(tab);
                                                        }

                                                        var reppan = tab.getComponent(0);



                                                        // Basic mask:

                                                        Ext.Object.merge(value, params);
                                                        var myMask= Ext.Msg.show({
                                                            title:'Отчеты...',
                                                            msg: 'Загрузка отчета.Ожидайте...',
                                                            buttons: Ext.Msg.CANCEL,
                                                            wait: true,
                                                            modal: true,
                                                            icon: Ext.Msg.INFO
                                                        });

                                                        QueryReport.getResults(value,function(data){
                                                            if (data){

                                                                //    reportHead.update(data.head);
                                                                reppan.update(data.content);
                                                                //      reportFoot.update(data.foot);
                                                                Ext.REPORTCONTENT =data.content;
                                                                Ext.REPORTSQL =data.sql;
                                                                Ext.REPORTTITLE =report;
                                                                myMask.close();


                                                            } else {
                                                                Ext.MessageBox.show({
                                                                    title: 'Ошибка ',
                                                                    msg: 'Документ не создан',
                                                                    buttons: Ext.MessageBox.OK,
                                                                    icon: Ext.MessageBox.ERROR

                                                                });
                                                                myMask.close();


                                                            }

                                                        });


                                                    }
                                                },
                                                x: 0,
                                                y: 30,
                                                height: 25,
                                                hidden: true,
                                                id: 'printRaspechatkaHouseMgkc',
                                                width: 180,
                                                icon: 'resources/css/images/printer.png',
                                                text: 'печать по квартирам',
                                                tooltip: 'Распечатка по выбранным квартирам'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'fieldset',
                                        x: 0,
                                        y: 100,
                                        height: 230,
                                        style: 'background-color: #e0e0e0;',
                                        width: 900,
                                        layout: 'absolute',
                                        title: 'Тарифы',
                                        items: [
                                            {
                                                xtype: 'checkboxfield',
                                                x: 0,
                                                y: 10,
                                                style: 'background-color: #f1eeee;',
                                                fieldLabel: 'тарифы установ вручную',
                                                name: 'tarif_manual',
                                                boxLabel: '',
                                                inputValue: '1',
                                                uncheckedValue: '0'
                                            },
                                            {
                                                xtype: 'fieldset',
                                                x: 130,
                                                y: 0,
                                                height: 120,
                                                style: 'background-color: #f1eeee;',
                                                width: 340,
                                                layout: 'absolute',
                                                title: 'дома до 12 этажей',
                                                items: [
                                                    {
                                                        xtype: 'fieldset',
                                                        x: 0,
                                                        y: 5,
                                                        style: 'background-color: #d3d3d3;',
                                                        width: 155,
                                                        checkboxName: '',
                                                        title: '1 этаж',
                                                        items: [
                                                            {
                                                                xtype: 'numberfield',
                                                                anchor: '100%',
                                                                width: 120,
                                                                fieldLabel: 'действ',
                                                                labelWidth: 45,
                                                                name: 'kv9f1',
                                                                hideTrigger: true,
                                                                decimalPrecision: 3
                                                            },
                                                            {
                                                                xtype: 'numberfield',
                                                                anchor: '100%',
                                                                width: 120,
                                                                fieldLabel: 'новый',
                                                                labelWidth: 45,
                                                                name: 'ch_kv9f1',
                                                                hideTrigger: true,
                                                                decimalPrecision: 3
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'fieldset',
                                                        x: 160,
                                                        y: 5,
                                                        style: 'background-color: #d3d3d3;',
                                                        width: 155,
                                                        title: '2 этаж и выше',
                                                        items: [
                                                            {
                                                                xtype: 'numberfield',
                                                                anchor: '100%',
                                                                width: 120,
                                                                fieldLabel: 'действ',
                                                                labelWidth: 45,
                                                                name: 'kv9',
                                                                hideTrigger: true,
                                                                decimalPrecision: 3
                                                            },
                                                            {
                                                                xtype: 'numberfield',
                                                                anchor: '100%',
                                                                width: 120,
                                                                fieldLabel: 'новый',
                                                                labelWidth: 45,
                                                                name: 'ch_kv9',
                                                                hideTrigger: true,
                                                                decimalPrecision: 3
                                                            }
                                                        ]
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'fieldset',
                                                x: 480,
                                                y: 0,
                                                height: 120,
                                                style: 'background-color: #f1eeee;',
                                                width: 350,
                                                layout: 'absolute',
                                                title: 'дома свыше 12 этажей',
                                                items: [
                                                    {
                                                        xtype: 'fieldset',
                                                        height: 80,
                                                        style: 'background-color: #d3d3d3;',
                                                        width: 155,
                                                        title: '1 этаж',
                                                        items: [
                                                            {
                                                                xtype: 'numberfield',
                                                                anchor: '100%',
                                                                width: 120,
                                                                fieldLabel: 'действ',
                                                                labelWidth: 45,
                                                                name: 'kv16f1',
                                                                hideTrigger: true,
                                                                decimalPrecision: 3
                                                            },
                                                            {
                                                                xtype: 'numberfield',
                                                                anchor: '100%',
                                                                width: 120,
                                                                fieldLabel: 'новый',
                                                                labelWidth: 45,
                                                                name: 'ch_kv16f1',
                                                                hideTrigger: true,
                                                                decimalPrecision: 3
                                                            }
                                                        ]
                                                    },
                                                    {
                                                        xtype: 'fieldset',
                                                        x: 165,
                                                        y: 5,
                                                        style: 'background-color: #d3d3d3;',
                                                        width: 155,
                                                        title: '2 этаж и выше',
                                                        items: [
                                                            {
                                                                xtype: 'numberfield',
                                                                anchor: '100%',
                                                                width: 120,
                                                                fieldLabel: 'действ',
                                                                labelWidth: 45,
                                                                name: 'kv16',
                                                                hideTrigger: true,
                                                                decimalPrecision: 3
                                                            },
                                                            {
                                                                xtype: 'numberfield',
                                                                anchor: '100%',
                                                                width: 120,
                                                                fieldLabel: 'новый',
                                                                labelWidth: 45,
                                                                name: 'ch_kv16',
                                                                hideTrigger: true,
                                                                decimalPrecision: 3
                                                            }
                                                        ]
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'textfield',
                                        x: 20,
                                        y: 250,
                                        style: 'background-color: #f1eeee;',
                                        width: 825,
                                        fieldLabel: 'Инфо перерасчета',
                                        labelWidth: 130,
                                        name: 'info',
                                        allowBlank: false
                                    }
                                ]
                            },
                            {
                                xtype: 'hiddenfield',
                                x: 295,
                                y: 210,
                                width: 115,
                                fieldLabel: 'Дом_ид',
                                labelWidth: 60,
                                name: 'house_id'
                            },
                            {
                                xtype: 'gridpanel',
                                x: 15,
                                y: 410,
                                height: 710,
                                id: 'grTarifHousesKv',
                                scrollable: true,
                                width: 940,
                                bodyBorder: true,
                                title: 'Дома',
                                store: 'StTarif',
                                dockedItems: [
                                    {
                                        xtype: 'toolbar',
                                        dock: 'top',
                                        items: [
                                            {
                                                xtype: 'combobox',
                                                width: 164,
                                                fieldLabel: 'Район',
                                                labelWidth: 45,
                                                name: 'raion_id',
                                                displayField: 'raion',
                                                queryMode: 'local',
                                                store: 'StRaionOrg',
                                                valueField: 'raion_id',
                                                listeners: {
                                                    select: 'onComboboxSelect2'
                                                }
                                            },
                                            {
                                                xtype: 'combobox',
                                                disabled: true,
                                                id: 'cbTarifKvartplata',
                                                width: 162,
                                                fieldLabel: 'услуга',
                                                labelWidth: 50,
                                                name: 'viborTarif',
                                                displayField: 'usluga',
                                                queryMode: 'local',
                                                store: 'StKvTarif',
                                                valueField: 'tarif',
                                                listeners: {
                                                    select: 'onCbTarifKvartplataSelect'
                                                }
                                            },
                                            {
                                                xtype: 'numberfield',
                                                id: 'tarKvartplata',
                                                width: 156,
                                                fieldLabel: 'тариф',
                                                labelWidth: 50,
                                                name: 'tar',
                                                value: 0,
                                                fieldStyle: 'background-color:#F0F8FF;font-size:10pt;text-align:right;',
                                                hideTrigger: true,
                                                decimalPrecision: 3
                                            },
                                            {
                                                xtype: 'button',
                                                handler: function(button, event) {
                                                    // in use
                                                    var value = button.findParentByType('form').getValues();
                                                    //STORE
                                                    var stUser = Ext.data.StoreManager.get("StUser");
                                                    var StTarif = Ext.data.StoreManager.get("StTarif");

                                                    //LOGIN & PASSWORD
                                                    var tarif = Ext.getCmp('tarKvartplata');
                                                    var viborTarif = Ext.getCmp('cbTarifKvartplata');
                                                    var btnNachHouseKvartplata = Ext.getCmp('btnNachHouseKvartplata');



                                                    //LOGIKA
                                                    var grid = Ext.getCmp('grTarifHousesKv');
                                                    //var viborTarif = Ext.getCmp('cbTarifKvartplata');

                                                    //var tarif = form.getForm().findField('tar');
                                                    var gridRowSelectedRecords  = grid.getView().getSelectionModel().getSelection();
                                                    var size = Ext.Object.getSize(gridRowSelectedRecords) ;
                                                    var values =stUser.getAt(0);
                                                    var login = values.get('login');
                                                    var password = values.get('password');
                                                    var params =[];
                                                    if (size >= 1){
                                                        params = {
                                                            login:values.get('login'),
                                                            password:values.get('password'),
                                                            what:"vvod_tarif_kvartplata",
                                                            name_tar:value.viborTarif,
                                                            new_tar:value.tar
                                                        };



                                                        Ext.Object.each(gridRowSelectedRecords, function(key, val, myself) {
                                                            Ext.Object.merge(val.data, params);
                                                            QueryAddress.updateRecords(val.data,function(results){
                                                                if(results.res){
                                                                    return  true;
                                                                }  else {
                                                                    return  false;
                                                                }
                                                            });

                                                        });

                                                        setTimeout(function(){
                                                            StTarif.load({
                                                                params: {
                                                                    what:'TarifFromRaion',
                                                                    login:login,
                                                                    password:password,
                                                                    what_id: value.raion_id
                                                                },
                                                                callback: function(records,operation,success){
                                                                    if(success){
                                                                        viborTarif.clearValue();
                                                                        viborTarif.setDisabled(true);
                                                                        btnNachHouseKvartplata.setDisabled(true);
                                                                        button.setDisabled(true);
                                                                        tarif.setValue(0);
                                                                    }
                                                                },
                                                                scope:this
                                                            });

                                                        }, 1000);
                                                    }
                                                },
                                                disabled: true,
                                                id: 'btnInsTarifKvartplata',
                                                width: 135,
                                                icon: 'resources/css/images/ico/yes.png',
                                                text: 'Записать тариф'
                                            },
                                            {
                                                xtype: 'tbfill'
                                            },
                                            {
                                                xtype: 'button',
                                                handler: function(button, event) {
                                                    //STORE
                                                    var stUser = Ext.data.StoreManager.get("StUser");
                                                    var grid = button.findParentByType('grid');
                                                    var getRowSelection = grid.getSelectionModel().getSelection()[0];
                                                    var house_id = getRowSelection.get('house_id');
                                                    //LOGIN & PASSWORD
                                                    var values =stUser.getAt(0);
                                                    var params = {
                                                        login:values.get('login'),
                                                        password:values.get('password'),
                                                        what:"nachislenie_kvartplata_house",
                                                        house_id:house_id
                                                    };
                                                    var gridRowSelectedRecords  = grid.getView().getSelectionModel().getSelection();
                                                    var size = Ext.Object.getSize(gridRowSelectedRecords) ;

                                                    if (size >1){
                                                        Ext.MessageBox.show({
                                                            title: 'Начисление квартплаты ',
                                                            msg: "Выберите только один дом ",
                                                            buttons: Ext.MessageBox.OK,
                                                            icon: Ext.MessageBox.INFO
                                                        });
                                                    } else {
                                                        //LOGIKA
                                                        var myMask= Ext.Msg.show({
                                                            title:'Начисление...',
                                                            msg: 'Начисление квартплаты по дому.Ожидайте...',
                                                            buttons: Ext.Msg.CANCEL,
                                                            wait: true,
                                                            modal: true,
                                                            icon: Ext.Msg.INFO
                                                        });
                                                        QueryAddress.updateRecords(params,function(results){
                                                            if(results.success==="1"){
                                                                myMask.close();
                                                                Ext.MessageBox.show({
                                                                    title: 'Начисление квартплаты ',
                                                                    msg: results.msg,
                                                                    buttons: Ext.MessageBox.OK,
                                                                    icon: Ext.MessageBox.INFO
                                                                });
                                                            } else {
                                                                myMask.close();
                                                                Ext.MessageBox.show({
                                                                    title: 'Начисление квартплаты',
                                                                    msg: results.msg,
                                                                    buttons: Ext.MessageBox.OK,
                                                                    icon: Ext.MessageBox.ERROR
                                                                });
                                                            }
                                                        });
                                                    }

                                                },
                                                formBind: false,
                                                disabled: true,
                                                id: 'btnNachHouseKvartplata',
                                                width: 134,
                                                icon: 'resources/css/images/ico/yes.png',
                                                text: 'Начислить дом'
                                            },
                                            {
                                                xtype: 'button',
                                                handler: function(button, event) {
                                                    //STORE
                                                    var stUser = Ext.data.StoreManager.get("StUser");
                                                    var grid = button.findParentByType('grid');
                                                    var getRowSelection = grid.getSelectionModel().getSelection()[0];
                                                    var house_id = getRowSelection.get('house_id');
                                                    //LOGIN & PASSWORD
                                                    var values =stUser.getAt(0);
                                                    var params = {
                                                        login:values.get('login'),
                                                        password:values.get('password'),
                                                        what:"FixDolgKvartplataOsmd",
                                                        house_id:house_id
                                                    };
                                                    var gridRowSelectedRecords  = grid.getView().getSelectionModel().getSelection();
                                                    var size = Ext.Object.getSize(gridRowSelectedRecords) ;

                                                    if (size >1){
                                                        Ext.MessageBox.show({
                                                            title: 'Фиксирование долга по квартплаты ОСМД',
                                                            msg: "Выберите только один дом ",
                                                            buttons: Ext.MessageBox.OK,
                                                            icon: Ext.MessageBox.INFO
                                                        });
                                                    } else {
                                                        //LOGIKA
                                                        var myMask= Ext.Msg.show({
                                                            title:'Начисление...',
                                                            msg: 'Фиксирование долга по квартплаты ОСМД.Ожидайте...',
                                                            buttons: Ext.Msg.CANCEL,
                                                            wait: true,
                                                            modal: true,
                                                            icon: Ext.Msg.INFO
                                                        });
                                                        QueryAddress.updateRecords(params,function(results){
                                                            if(results.success==="1"){
                                                                myMask.close();
                                                                Ext.MessageBox.show({
                                                                    title: 'Фиксирование долга по квартплаты ОСМД ',
                                                                    msg: results.msg,
                                                                    buttons: Ext.MessageBox.OK,
                                                                    icon: Ext.MessageBox.INFO
                                                                });
                                                            } else {
                                                                myMask.close();
                                                                Ext.MessageBox.show({
                                                                    title: 'Фиксирование долга по квартплаты ОСМД',
                                                                    msg: results.msg,
                                                                    buttons: Ext.MessageBox.OK,
                                                                    icon: Ext.MessageBox.ERROR
                                                                });
                                                            }
                                                        });
                                                    }

                                                },
                                                formBind: false,
                                                disabled: true,
                                                id: 'btnFixKvartplata',
                                                width: 84,
                                                icon: 'resources/css/images/ico/yes.png',
                                                text: 'Осмд'
                                            },
                                            {
                                                xtype: 'button',
                                                handler: function(button, event) {
                                                    var value = button.findParentByType('form').getValues();
                                                    var StUser = Ext.data.StoreManager.get("StUser");
                                                    var StReport = Ext.data.StoreManager.get("StReport");
                                                    var values =StUser.getAt(0);

                                                    //console.log(value);

                                                    var usertype = 1;

                                                    var tabPnCenter =  Ext.getCmp('tabPnCenter');//me.getTabPnCenter();



                                                    if (value.house_id !==0) {

                                                        var report = 'HouseRaspechatkaMgkc';
                                                        var namereport = 'Распечатка дома';

                                                        var params = {
                                                            login:values.get('login'),
                                                            password:values.get('password'),
                                                            report:report,
                                                            what:report
                                                        };

                                                        var tab = tabPnCenter.child('#'+report);

                                                        if (!tab) {
                                                            tab  = tabPnCenter.add({
                                                                xtype:'tabreportorg',
                                                                title:namereport,
                                                                id:''+report+''
                                                            });

                                                            tabPnCenter.setActiveTab(tab);

                                                        }else{

                                                            tabPnCenter.setActiveTab(tab);
                                                        }

                                                        var reppan = tab.getComponent(0);



                                                        // Basic mask:

                                                        Ext.Object.merge(value, params);
                                                        var myMask= Ext.Msg.show({
                                                            title:'Отчеты...',
                                                            msg: 'Загрузка отчета.Ожидайте...',
                                                            buttons: Ext.Msg.CANCEL,
                                                            wait: true,
                                                            modal: true,
                                                            icon: Ext.Msg.INFO
                                                        });

                                                        QueryReport.getResults(value,function(data){
                                                            if (data){

                                                                //    reportHead.update(data.head);
                                                                reppan.update(data.content);
                                                                //      reportFoot.update(data.foot);
                                                                Ext.REPORTCONTENT =data.content;
                                                                Ext.REPORTSQL =data.sql;
                                                                Ext.REPORTTITLE =report;
                                                                myMask.close();


                                                            } else {
                                                                Ext.MessageBox.show({
                                                                    title: 'Ошибка ',
                                                                    msg: 'Документ не создан',
                                                                    buttons: Ext.MessageBox.OK,
                                                                    icon: Ext.MessageBox.ERROR

                                                                });
                                                                myMask.close();


                                                            }

                                                        });


                                                    }
                                                },
                                                disabled: true,
                                                id: 'printRaspechatkaHouseAllMgkc',
                                                width: 27,
                                                icon: 'resources/css/images/ico/printerplus.png',
                                                text: '',
                                                tooltip: 'Распечатка по дому'
                                            }
                                        ]
                                    }
                                ],
                                selModel: Ext.create('Ext.selection.CheckboxModel', {
                                    selType: 'checkboxmodel',
                                    showHeaderCheckbox: true
                                }),
                                columns: [
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'raion',
                                        text: 'Raion'
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        text: 'Дом',
                                        columns: [
                                            {
                                                xtype: 'numbercolumn',
                                                width: 60,
                                                dataIndex: 'house_id',
                                                menuDisabled: true,
                                                text: 'ид',
                                                format: '0'
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                width: 159,
                                                dataIndex: 'house',
                                                menuDisabled: true,
                                                text: 'Адрес'
                                            },
                                            {
                                                xtype: 'numbercolumn',
                                                width: 47,
                                                dataIndex: 'floor',
                                                menuDisabled: true,
                                                text: 'Эт',
                                                format: '0'
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        text: 'Квартплата дома до 12эт',
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                menuDisabled: true,
                                                text: '1 этаж',
                                                columns: [
                                                    {
                                                        xtype: 'numbercolumn',
                                                        width: 86,
                                                        align: 'right',
                                                        dataIndex: 'kv9f1',
                                                        menuDisabled: true,
                                                        text: 'тариф',
                                                        format: '0.000'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        width: 84,
                                                        align: 'right',
                                                        dataIndex: 'ch_kv9f1',
                                                        menuDisabled: true,
                                                        text: 'перер',
                                                        format: '0.000'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                menuDisabled: true,
                                                text: '2й и выше',
                                                columns: [
                                                    {
                                                        xtype: 'numbercolumn',
                                                        width: 85,
                                                        align: 'right',
                                                        dataIndex: 'kv9',
                                                        menuDisabled: true,
                                                        text: 'тариф',
                                                        format: '0.000'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        width: 77,
                                                        align: 'right',
                                                        dataIndex: 'ch_kv9',
                                                        menuDisabled: true,
                                                        text: 'перер',
                                                        format: '0.000'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'gridcolumn',
                                        text: 'Квартплата дома свыше 12эт',
                                        columns: [
                                            {
                                                xtype: 'gridcolumn',
                                                text: '1 этаж',
                                                columns: [
                                                    {
                                                        xtype: 'numbercolumn',
                                                        width: 86,
                                                        align: 'right',
                                                        dataIndex: 'kv16f1',
                                                        menuDisabled: true,
                                                        text: 'тариф',
                                                        format: '0.000'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        width: 73,
                                                        align: 'right',
                                                        dataIndex: 'ch_kv16f1',
                                                        menuDisabled: true,
                                                        text: 'перер',
                                                        format: '0.000'
                                                    }
                                                ]
                                            },
                                            {
                                                xtype: 'gridcolumn',
                                                text: '2й и выше',
                                                columns: [
                                                    {
                                                        xtype: 'numbercolumn',
                                                        width: 77,
                                                        align: 'right',
                                                        dataIndex: 'kv16',
                                                        menuDisabled: true,
                                                        text: 'тариф',
                                                        format: '0.000'
                                                    },
                                                    {
                                                        xtype: 'numbercolumn',
                                                        width: 65,
                                                        align: 'right',
                                                        dataIndex: 'ch_kv16',
                                                        menuDisabled: true,
                                                        text: 'перер',
                                                        format: '0.000'
                                                    }
                                                ]
                                            }
                                        ]
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'otoplenie',
                                        text: 'Otoplenie'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'ch_otoplenie',
                                        text: 'Ch_otoplenie'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'podogrev',
                                        text: 'Podogrev'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'ch_podogrev',
                                        text: 'Ch_podogrev'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'gv9',
                                        text: 'Gv9'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'ch_gv9',
                                        text: 'Ch_gv9'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'gv16',
                                        text: 'Gv16'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'ch_gv16',
                                        text: 'Ch_gv16'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'xv9',
                                        text: 'Xv9'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'ch_xv9',
                                        text: 'Ch_xv9'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'xv16',
                                        text: 'Xv16'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'ch_xv16',
                                        text: 'Ch_xv16'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'stoki',
                                        text: 'Stoki'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'ch_stoki',
                                        text: 'Ch_stoki'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'st9',
                                        text: 'St9'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'ch_st9',
                                        text: 'Ch_st9'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'st16',
                                        text: 'St16'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'ch_st16',
                                        text: 'Ch_st16'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'tbo',
                                        text: 'Tbo'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'ch_tbo',
                                        text: 'Ch_tbo'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'xvkub',
                                        text: 'Xvkub'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'gvkub',
                                        text: 'Gvkub'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'xvkub_lg',
                                        text: 'Xvkub_lg'
                                    },
                                    {
                                        xtype: 'numbercolumn',
                                        hidden: true,
                                        dataIndex: 'gvkub_lg',
                                        text: 'Gvkub_lg'
                                    }
                                ]
                            },
                            {
                                xtype: 'button',
                                handler: function(button, event) {
                                    //STORE
                                    var stUser = Ext.data.StoreManager.get("StUser");

                                    var values =stUser.getAt(0);
                                    var login = values.get('login');
                                    var password = values.get('password');

                                    params = {
                                        login:values.get('login'),
                                        password:values.get('password'),
                                        what:"clear_pr_kvartplata"

                                    };
                                    QueryAddress.updateRecords(params,function(results){
                                        if(results.res){
                                            Ext.MessageBox.show({
                                                title: 'Сброс защиты ',
                                                msg: 'Можно начислять квартплату',
                                                buttons: Ext.MessageBox.OK,
                                                icon: Ext.MessageBox.INFO
                                            });

                                        }
                                    });



                                },
                                x: 850,
                                y: 27,
                                id: 'btnClearNachKv',
                                width: 25,
                                icon: 'resources/css/images/ico/no.png',
                                iconAlign: 'bottom',
                                text: '',
                                tooltip: 'Сброс признака <br>картплата начислена'
                            }
                        ]
                    }
                ]
            };
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    onDatefieldSelect: function(field, value, eOpts) {
        var btAddNach = Ext.getCmp('btAddNachKv');
        var btAddPerer = Ext.getCmp('btAddPererKv');
        var pnPerer = Ext.getCmp('pnPererKv');
        pnPerer.setTitle("Перерасчет квартплаты за период "+ Ext.Date.format(value, 'F,Y'));
        btAddNach.setText("Начислить квартплату за период  "+ Ext.Date.format(value, 'F,Y'));
        btAddPerer.setText("Перерасчитать вквартплату за  "+ Ext.Date.format(value, 'F,Y'));
    },

    onComboboxSelect2: function(combo, record, eOpts) {
        //in use

        //STORE
        var stUser = Ext.data.StoreManager.get("StUser");
        var StTarif = Ext.data.StoreManager.get("StTarif");
        var tarif = Ext.getCmp('tarKvartplata');
        var viborTarif = Ext.getCmp('cbTarifKvartplata');


        //LOGIN & PASSWORD

        var values =stUser.getAt(0);
        var login = values.get('login');
        var password = values.get('password');

        //LOGIKA
        if (record) {
            StTarif.load({
                params: {
                    what:'TarifFromRaion',
                    login:login,
                    password:password,
                    what_id: record.get('raion_id')
                },
                callback: function(records,operation,success){
                    if(success){
                        viborTarif.clearValue();
                        viborTarif.setDisabled(true);
                        tarif.setValue(0);
                    }
                },
                scope:this
            });
        }
    },

    onCbTarifKvartplataSelect: function(combo, record, eOpts) {
        //in use

        //STORE

        var form = combo.findParentByType('form');
        var tarif = form.getForm().findField('tar');
        //var values =StTarif.getAt(0);
        var grid = Ext.getCmp('grTarifHousesKv');
        var btnInsTarifKvartplata = Ext.getCmp('btnInsTarifKvartplata');
        var selected = record;

        if (record) {
            //  var gridRowSelectedRecords  = grid.getView().getSelectionModel().getSelection();
            var gridRowSelectedRecords  = grid.getView().getSelectionModel().getSelection()[0];

            var size = Ext.Object.getSize(gridRowSelectedRecords) ;
            btnInsTarifKvartplata.setDisabled(false);

            // if (size !==0){
            //    Ext.Object.each(gridRowSelectedRecords, function(key, val, myself) {

            //       tarif.setValue(val.get(records[0].get('tarif')));
            tarif.setValue(gridRowSelectedRecords.get(record.get('tarif')));

            // });
            //  }
        }


    }

});