/*
 * File: app/view/sprav/TabPB.js
 * Date: Sat Sep 12 2020 19:51:40 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ykis.view.sprav.TabPB', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tabpb',

    requires: [
        'Ykis.view.sprav.TabPBViewModel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button',
        'Ext.toolbar.Separator',
        'Ext.form.field.Date',
        'Ext.form.field.Hidden',
        'Ext.grid.column.Action',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.form.field.Number',
        'Ext.grid.plugin.RowEditing',
        'Ext.selection.CheckboxModel',
        'Ext.grid.feature.GroupingSummary',
        'Ext.grid.feature.Summary'
    ],

    viewModel: {
        type: 'tabpb'
    },
    height: 800,
    id: 'tabPB',
    scrollable: true,
    layout: 'fit',
    closable: true,
    title: 'Оплата ПРИВАТБАНК',
    defaultListenerScope: true,

    items: [
        {
            xtype: 'gridpanel',
            id: 'grPB',
            scrollable: true,
            collapseFirst: false,
            title: '',
            store: 'StPB',
            viewConfig: {
                getRowClass: function(record, rowIndex, rowParams, store) {

                    if(record.get('pr') === 0 ){

                        return 'change_color_yellow';
                    }
                    else if(record.get('pr') === 1 ){
                        return  'change_color_green';

                    } else  {
                        return  'change_color_red';
                    }

                },
                emptyText: 'Платежи не загружены',
                selectedItemCls: 'x-grid-item-selected change_color_pb'
            },
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    height: 45,
                    items: [
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var data =  Ext.getCmp('search_date_pb').getValue();
                                var StPB = Ext.data.StoreManager.get("StPB");

                                var stUser = Ext.data.StoreManager.get("StUser");

                                //LOGIN & PASSWORD
                                var values =stUser.getAt(0);
                                var value = {
                                    login:values.get('login'),
                                    password:values.get('password'),
                                    data:data,
                                    what:"delOplataPbEmpty"
                                };


                                Ext.MessageBox.confirm({
                                    title: 'Удаление записи',
                                    msg: 'Вы удаляете записи об оплате  <br> Подтвердите или отмените свои действия.',
                                    buttons: Ext.MessageBox.OKCANCEL,
                                    icon: Ext.MessageBox.ERROR,
                                    buttonText:{
                                        ok:'подтвеждаю',
                                        cancel:'отмена'
                                    },
                                    fn:function(btn,newValue){
                                        if(btn=='ok'){
                                            QueryKassa.delOplata(value,function(results){
                                                if(results.success==="1"){
                                                    Ext.MessageBox.show({
                                                        title: 'Удаление записи об оплате ',
                                                        msg: results.msg,
                                                        buttons: Ext.MessageBox.OK,
                                                        icon: Ext.MessageBox.INFO
                                                    });
                                                    StPB.load({
                                                        params: {
                                                            what:'getPBdata',
                                                            data:data,
                                                            login:values.get('login'),
                                                            password:values.get('password')
                                                        }
                                                    });

                                                } else {
                                                    Ext.MessageBox.show({
                                                        title: 'Удаление записи об оплате',
                                                        msg: results.msg,
                                                        buttons: Ext.MessageBox.OK,
                                                        icon: Ext.MessageBox.ERROR
                                                    });
                                                }
                                            });
                                        }
                                    }
                                });

                            },
                            icon: 'resources/css/images/ico/s_error.png',
                            text: '',
                            tooltip: 'Удалить пустые записи',
                            tooltipType: 'title'
                        },
                        {
                            xtype: 'tbseparator',
                            width: 20
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                //in use
                                var winImport = Ext.ClassManager.instantiateByAlias('widget.winimport');
                                var form = Ext.getCmp('fmImport');
                                var vibor =  'privatbank';
                                winImport.setTitle('Загрузка реестра  из ПриватБанка)');

                                winImport.show();

                                form.getForm().findField('vibor').setValue(vibor);


                            },
                            id: 'btnImportPB',
                            width: 140,
                            icon: 'resources/css/images/ico/door_in.png',
                            text: 'Импорт реестров'
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'datefield',
                            id: 'search_date_pb',
                            width: 200,
                            fieldLabel: 'Поиск по дате',
                            labelWidth: 80,
                            format: 'd-m-Y',
                            submitFormat: 'Ymd',
                            listeners: {
                                change: 'onDatefieldChange'
                            }
                        },
                        {
                            xtype: 'tbseparator'
                        },
                        {
                            xtype: 'button',
                            handler: function(button, event) {
                                var stUser = Ext.data.StoreManager.get("StUser");
                                var StPB = Ext.data.StoreManager.get("StPB");
                                var data =  Ext.getCmp('search_date_pb').getValue();

                                var values =stUser.getAt(0);
                                StPB.load({
                                    params: {
                                        what:'getPB',
                                        data:data,
                                        login:values.get('login'),
                                        password:values.get('password')
                                    }
                                });

                            },
                            disabled: true,
                            height: 25,
                            id: 'btnUpdatePbReestr',
                            width: 126,
                            icon: 'resources/css/images/ico/xsldbg_refresh.png',
                            text: 'Оновить  дані'
                        },
                        {
                            xtype: 'button',
                            height: 25,
                            id: 'PBKassaYKIS',
                            width: 167,
                            icon: 'resources/css/images/ico/printer.png',
                            text: 'Реестр по адресам ЮКИС'
                        },
                        {
                            xtype: 'button',
                            height: 25,
                            id: 'PBKassaYKISdata',
                            width: 167,
                            icon: 'resources/css/images/ico/printer.png',
                            text: 'Реестр по дате ЮКИС'
                        },
                        {
                            xtype: 'button',
                            height: 25,
                            id: 'PBKassaOSBB',
                            width: 167,
                            icon: 'resources/css/images/ico/printer.png',
                            text: 'Реестр по ОСББ'
                        },
                        {
                            xtype: 'hiddenfield',
                            fieldLabel: 'Label',
                            name: 'usluga'
                        }
                    ]
                }
            ],
            columns: [
                {
                    xtype: 'actioncolumn',
                    width: 30,
                    menuDisabled: true,
                    tooltip: 'Удалить запись',
                    tooltipType: 'title',
                    altText: 'Удалить запись',
                    items: [
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                // in use
                                var me = this;
                                //STORE

                                var stUser = Ext.data.StoreManager.get("StUser");
                                var grid = view.findParentByType('grid');
                                var data =  Ext.getCmp('search_date_pb').getValue();

                                var store = view.getStore();
                                var plugin = grid.getPlugin('rowEditPb');
                                plugin.cancelEdit();

                                //LOGIN & PASSWORD
                                var values =stUser.getAt(0);
                                var params = {
                                    login:values.get('login'),
                                    password:values.get('password'),
                                    address_id:values.get('address_id'),
                                    address:values.get('address'),
                                    what:"delOplataPb"
                                };

                                //GRID
                                var value = record.data;


                                //LOGIKA


                                Ext.Object.merge(value, params);

                                Ext.MessageBox.confirm({
                                    title: 'Удаление записи',
                                    msg: 'Вы удаляете запись об оплате  <br> Подтвердите или отмените свои действия.',
                                    buttons: Ext.MessageBox.OKCANCEL,
                                    icon: Ext.MessageBox.ERROR,
                                    buttonText:{
                                        ok:'подтвеждаю',
                                        cancel:'отмена'
                                    },
                                    fn:function(btn,newValue){
                                        if(btn=='ok'){
                                            QueryKassa.delOplata(value,function(results){
                                                if(results.success==="1"){
                                                    Ext.MessageBox.show({
                                                        title: 'Удаление записи об оплате ',
                                                        msg: results.msg,
                                                        buttons: Ext.MessageBox.OK,
                                                        icon: Ext.MessageBox.INFO
                                                    });
                                                    store.load({
                                                        params: {
                                                            what:'getPB',
                                                            data:data,
                                                            login:values.get('login'),
                                                            password:values.get('password')
                                                        },
                                                        scope:this
                                                    });

                                                } else {
                                                    Ext.MessageBox.show({
                                                        title: 'Удаление записи об оплате',
                                                        msg: results.msg,
                                                        buttons: Ext.MessageBox.OK,
                                                        icon: Ext.MessageBox.ERROR
                                                    });
                                                }
                                            });
                                        }
                                    }
                                });
                            },
                            getClass: function(v, metadata, r, rowIndex, colIndex, store) {
                                var pr = r.get('pr');

                                if (pr === 0 ) {
                                    metaData = 'x-grid-center-icon';
                                }  else if (pr === 1 || pr === 2 ) {
                                    metaData = 'x-hide-display';

                                }
                                return metaData;
                            },
                            icon: 'resources/css/images/ico/no.png'
                        },
                        {
                            handler: function(view, rowIndex, colIndex, item, e, record, row) {
                                // in use
                                var me = this;
                                //STORE

                                var stUser = Ext.data.StoreManager.get("StUser");
                                var grid = view.findParentByType('grid');
                                var data =  Ext.getCmp('search_date_pb').getValue();

                                var store = view.getStore();
                                var plugin = grid.getPlugin('rowEditPb');
                                plugin.cancelEdit();

                                //LOGIN & PASSWORD
                                var values =stUser.getAt(0);
                                var params = {
                                    login:values.get('login'),
                                    password:values.get('password'),
                                    address_id:values.get('address_id'),
                                    address:values.get('address'),
                                    what:"PrivatBank_oplata_add"
                                };

                                //GRID
                                var value = record.data;


                                //LOGIKA


                                Ext.Object.merge(value, params);

                                Ext.MessageBox.confirm({
                                    title: 'Ввод  записи в оплату',
                                    msg: 'Ввод  записи в оплату  <br> Подтвердите или отмените свои действия.',
                                    buttons: Ext.MessageBox.OKCANCEL,
                                    icon: Ext.MessageBox.ERROR,
                                    buttonText:{
                                        ok:'подтвеждаю',
                                        cancel:'отмена'
                                    },
                                    fn:function(btn,newValue){
                                        if(btn=='ok'){
                                            QueryKassa.delOplata(value,function(results){
                                                if(results.success==="1"){
                                                    Ext.MessageBox.show({
                                                        title: 'Ввод  записи в оплату ',
                                                        msg: results.msg,
                                                        buttons: Ext.MessageBox.OK,
                                                        icon: Ext.MessageBox.INFO
                                                    });
                                                    store.load({
                                                        params: {
                                                            what:'getPB',
                                                            data:data,
                                                            login:values.get('login'),
                                                            password:values.get('password')
                                                        },
                                                        scope:this
                                                    });

                                                } else {
                                                    Ext.MessageBox.show({
                                                        title: 'Ввод  записи в оплату',
                                                        msg: results.msg,
                                                        buttons: Ext.MessageBox.OK,
                                                        icon: Ext.MessageBox.ERROR
                                                    });
                                                }
                                            });
                                        }
                                    }
                                });
                            },
                            getClass: function(v, metadata, r, rowIndex, colIndex, store) {
                                var pr = r.get('pr');

                                if (pr === 2 ) {
                                    metaData = 'x-grid-center-icon';
                                }  else if (pr === 0 || pr === 1 ) {
                                    metaData = 'x-hide-display';

                                }
                                return metaData;
                            },
                            icon: 'resources/css/images/ico/add.png'
                        }
                    ]
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    width: 60,
                    dataIndex: 'payment_id',
                    menuDisabled: true,
                    text: 'Запись',
                    format: '0'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    width: 60,
                    dataIndex: 'period',
                    menuDisabled: true,
                    text: 'Период',
                    format: '0'
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    width: 55,
                    dataIndex: 'raion_id',
                    menuDisabled: true,
                    text: 'Район',
                    format: '0'
                },
                {
                    xtype: 'datecolumn',
                    width: 80,
                    dataIndex: 'data',
                    menuDisabled: true,
                    text: 'Дата',
                    format: 'd-m-Y'
                },
                {
                    xtype: 'numbercolumn',
                    items: {
                        xtype: 'textfield',
                        flex: 1,
                        margin: 2,
                        enableKeyEvents: true,
                        listeners: {
                            keyup: function() {
                                            var store = this.up('tablepanel').store;
                                            store.clearFilter();
                                            if (this.value) {
                                                store.filter({
                                                    property     : 'pay_id',
                                                    value         : this.value,
                                                    anyMatch      : true,
                                                    caseSensitive : false
                                                });
                                            }
                                        },
                            buffer: 1000
                        }
                    },
                    width: 85,
                    dataIndex: 'pay_id',
                    menuDisabled: true,
                    text: 'Ид платежа',
                    format: '0'
                },
                {
                    xtype: 'gridcolumn',
                    items: {
                        xtype: 'textfield',
                        flex: 1,
                        margin: 2,
                        enableKeyEvents: true,
                        listeners: {
                            keyup: function() {
                                            var store = this.up('tablepanel').store;
                                            store.clearFilter();
                                            if (this.value) {
                                                store.filter({
                                                    property     : 'pay_nomer',
                                                    value         : this.value,
                                                    anyMatch      : true,
                                                    caseSensitive : false
                                                });
                                            }
                                        },
                            buffer: 1000
                        }
                    },
                    width: 116,
                    dataIndex: 'pay_nomer',
                    menuDisabled: true,
                    text: '№ платежа'
                },
                {
                    xtype: 'numbercolumn',
                    items: {
                        xtype: 'textfield',
                        flex: 1,
                        margin: 2,
                        enableKeyEvents: true,
                        listeners: {
                            keyup: function() {
                                            var store = this.up('tablepanel').store;
                                            store.clearFilter();
                                            if (this.value) {
                                                store.filter({
                                                    property     : 'address_id',
                                                    value         : this.value,
                                                    anyMatch      : true,
                                                    caseSensitive : false
                                                });
                                            }
                                        },
                            buffer: 1000
                        }
                    },
                    width: 50,
                    dataIndex: 'address_id',
                    menuDisabled: true,
                    text: 'лс',
                    format: '0'
                },
                {
                    xtype: 'gridcolumn',
                    items: {
                        xtype: 'textfield',
                        flex: 1,
                        margin: 2,
                        enableKeyEvents: true,
                        listeners: {
                            keyup: function() {
                                            var store = this.up('tablepanel').store;
                                            store.clearFilter();
                                            if (this.value) {
                                                store.filter({
                                                    property     : 'address',
                                                    value         : this.value,
                                                    anyMatch      : true,
                                                    caseSensitive : false
                                                });
                                            }
                                        },
                            buffer: 1000
                        }
                    },
                    width: 125,
                    dataIndex: 'address',
                    menuDisabled: true,
                    text: 'Адрес'
                },
                {
                    xtype: 'gridcolumn',
                    items: {
                        xtype: 'textfield',
                        flex: 1,
                        margin: 2,
                        enableKeyEvents: true,
                        listeners: {
                            keyup: function() {
                                            var store = this.up('tablepanel').store;
                                            store.clearFilter();
                                            if (this.value) {
                                                store.filter({
                                                    property     : 'fio',
                                                    value         : this.value,
                                                    anyMatch      : true,
                                                    caseSensitive : false
                                                });
                                            }
                                        },
                            buffer: 1000
                        }
                    },
                    width: 120,
                    dataIndex: 'fio',
                    menuDisabled: true,
                    text: 'Ф.И.О'
                },
                {
                    xtype: 'numbercolumn',
                    width: 40,
                    dataIndex: 'pr',
                    menuDisabled: true,
                    text: 'Пр',
                    format: '0',
                    editor: {
                        xtype: 'numberfield'
                    }
                },
                {
                    xtype: 'numbercolumn',
                    summaryRenderer: function(val, params, data) {
                        var n =Ext.util.Format.number(val,'0,000.00');
                        if (val >= 0) {
                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                        } else  {
                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                        }
                    },
                    summaryType: 'sum',
                    width: 70,
                    dataIndex: 'kvartplata',
                    menuDisabled: true,
                    text: 'Кварт'
                },
                {
                    xtype: 'numbercolumn',
                    summaryRenderer: function(val, params, data) {
                        var n =Ext.util.Format.number(val,'0,000.00');
                        if (val >= 0) {
                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                        } else  {
                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                        }
                    },
                    summaryType: 'sum',
                    width: 55,
                    dataIndex: 'rfond',
                    menuDisabled: true,
                    text: 'Р.Фонд'
                },
                {
                    xtype: 'numbercolumn',
                    summaryRenderer: function(val, params, data) {
                        var n =Ext.util.Format.number(val,'0,000.00');
                        if (val >= 0) {
                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                        } else  {
                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                        }
                    },
                    summaryType: 'sum',
                    width: 70,
                    dataIndex: 'voda',
                    menuDisabled: true,
                    text: 'Вода'
                },
                {
                    xtype: 'numbercolumn',
                    summaryRenderer: function(val, params, data) {
                        var n =Ext.util.Format.number(val,'0,000.00');
                        if (val >= 0) {
                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                        } else  {
                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                        }
                    },
                    summaryType: 'sum',
                    width: 70,
                    dataIndex: 'stoki',
                    menuDisabled: true,
                    text: 'Стоки'
                },
                {
                    xtype: 'numbercolumn',
                    summaryRenderer: function(val, params, data) {
                        var n =Ext.util.Format.number(val,'0,000.00');
                        if (val >= 0) {
                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                        } else  {
                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                        }
                    },
                    summaryType: 'sum',
                    width: 75,
                    dataIndex: 'otoplenie',
                    menuDisabled: true,
                    text: 'Отопл'
                },
                {
                    xtype: 'numbercolumn',
                    summaryRenderer: function(val, params, data) {
                        var n =Ext.util.Format.number(val,'0,000.00');
                        if (val >= 0) {
                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                        } else  {
                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                        }
                    },
                    summaryType: 'sum',
                    width: 70,
                    dataIndex: 'ptn',
                    menuDisabled: true,
                    text: 'ПТН'
                },
                {
                    xtype: 'numbercolumn',
                    summaryRenderer: function(val, params, data) {
                        var n =Ext.util.Format.number(val,'0,000.00');
                        if (val >= 0) {
                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                        } else  {
                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                        }
                    },
                    summaryType: 'sum',
                    width: 60,
                    dataIndex: 'tbo',
                    menuDisabled: true,
                    text: 'ТБО'
                },
                {
                    xtype: 'numbercolumn',
                    summaryRenderer: function(val, params, data) {
                        var n =Ext.util.Format.number(val,'0,000.00');
                        if (val >= 0) {
                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                        } else  {
                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                        }
                    },
                    summaryType: 'sum',
                    width: 61,
                    dataIndex: 'energy',
                    menuDisabled: true,
                    text: 'Енергия'
                },
                {
                    xtype: 'numbercolumn',
                    summaryRenderer: function(val, params, data) {
                        var n =Ext.util.Format.number(val,'0,000.00');
                        if (val >= 0) {
                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                        } else  {
                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                        }
                    },
                    summaryType: 'sum',
                    width: 54,
                    dataIndex: 'vaxta',
                    menuDisabled: true,
                    text: 'Вахта'
                },
                {
                    xtype: 'numbercolumn',
                    summaryRenderer: function(val, params, data) {
                        var n =Ext.util.Format.number(val,'0,000.00');
                        if (val >= 0) {
                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                        } else  {
                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                        }
                    },
                    summaryType: 'sum',
                    width: 60,
                    dataIndex: 'ddolg',
                    menuDisabled: true,
                    text: 'Долг<br>Добр'
                },
                {
                    xtype: 'numbercolumn',
                    summaryRenderer: function(val, params, data) {
                        var n =Ext.util.Format.number(val,'0,000.00');
                        if (val >= 0) {
                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                        } else  {
                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                        }
                    },
                    summaryType: 'sum',
                    width: 49,
                    dataIndex: 'fdolg',
                    menuDisabled: true,
                    text: 'Долг<br>МЖКЦ'
                },
                {
                    xtype: 'numbercolumn',
                    summaryRenderer: function(val, params, data) {
                        var n =Ext.util.Format.number(val,'0,000.00');
                        if (val >= 0) {
                            return '<span style="color:#000; font-weight:bold;">' + n + '</span>';
                        } else  {
                            return '<span style="color:red; font-weight:bold;">' + n + '</span>';
                        }
                    },
                    summaryType: 'sum',
                    width: 90,
                    dataIndex: 'summa',
                    menuDisabled: true,
                    text: 'Сумма'
                },
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    dataIndex: 'rec_id',
                    menuDisabled: true,
                    text: 'Оплата<br>YIS',
                    format: '0',
                    editor: {
                        xtype: 'numberfield'
                    }
                },
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    dataIndex: 'osbb_rec_id',
                    menuDisabled: true,
                    text: 'Оплата<br>ОСББ',
                    format: '0',
                    editor: {
                        xtype: 'numberfield'
                    }
                },
                {
                    xtype: 'datecolumn',
                    width: 87,
                    dataIndex: 'date_create',
                    menuDisabled: true,
                    text: 'дата_созд',
                    format: 'd-m-Y h:m:s'
                },
                {
                    xtype: 'datecolumn',
                    width: 87,
                    dataIndex: 'date_confirm',
                    menuDisabled: true,
                    text: 'дата_опл',
                    format: 'd-m-Y h:m:s'
                }
            ],
            plugins: [
                {
                    ptype: 'rowediting',
                    pluginId: 'rowEditPb',
                    listeners: {
                        edit: 'onRowEditingEdit'
                    }
                }
            ],
            selModel: {
                selType: 'checkboxmodel',
                mode: 'SINGLE'
            },
            features: [
                {
                    ftype: 'groupingsummary',
                    id: 'groupPB',
                    startCollapsed: true
                },
                {
                    ftype: 'summary',
                    dock: 'top'
                }
            ]
        }
    ],

    onDatefieldChange: function(field, newValue, oldValue, eOpts) {
        var stUser = Ext.data.StoreManager.get("StUser");
        var StPB = Ext.data.StoreManager.get("StPB");
        var values =stUser.getAt(0);
        var btnUpdatePbReestr =  Ext.getCmp('btnUpdatePbReestr');
        btnUpdatePbReestr.setDisabled(false);
        StPB.load({
            params: {
                what:'getPBdata',
                data:newValue,
                login:values.get('login'),
                password:values.get('password')
            }
        });

    },

    onRowEditingEdit: function(editor, context, eOpts) {
        var grid = editor.grid;
        var store = grid.getStore();
        var sm = store.getUpdatedRecords();
        var data = grid.getSelectionModel();
        if(sm.length) {

            store.sync({

                success: function(){
                    store.load();
                },
                scope:this
            });
        }

    }

});