/*
 * File: app/view/sprav/TabSubsidiaViewController.js
 * Date: Sat Nov 30 2019 21:19:19 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ykis.view.sprav.TabSubsidiaViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.tabsubsidia',

    onDataNachSubsidiaChange: function(field, newValue, oldValue, eOpts) {

        //STORE
        var stUser = Ext.data.StoreManager.get("StUser");
        var values =stUser.getAt(0);
        var login = values.get('login');
        var password = values.get('password');

        var stSubsidia = Ext.data.StoreManager.get("StSubsidia");
        var usluga_id =  Ext.getCmp('orgOshaBank').getValue();

        var btnGetSubsidiaOshadBank =  Ext.getCmp('btnGetSubsidiaOshadBank');
        var btnPrintSubsReestrFromOshadBank =  Ext.getCmp('btnPrintSubsReestrFromOshadBank');
        var btnPrintSubsReestrToOshadBank =  Ext.getCmp('btnPrintSubsReestrToOshadBank');
        var btnImportOshadBank =  Ext.getCmp('btnImportOshadBank');
        var btnExportOshadBank =  Ext.getCmp('btnExportOshadBank');
        var btnImportOplataOshad =  Ext.getCmp('btnImportOplataOshad');
        var btnImportOplataYkis =  Ext.getCmp('btnImportOplataYkis');
        var btnSubsidiaOtkat =  Ext.getCmp('btnSubsidiaOtkat');


        if (usluga_id){
            btnGetSubsidiaOshadBank.setDisabled(false);
            btnPrintSubsReestrFromOshadBank.setDisabled(false);
            btnPrintSubsReestrToOshadBank.setDisabled(false);
            btnImportOshadBank.setDisabled(false);
            btnExportOshadBank.setDisabled(false);
            btnImportOplataOshad.setDisabled(false);
            btnImportOplataYkis.setDisabled(false);
            btnSubsidiaOtkat.setDisabled(false);


            stSubsidia.load({
                params: {
                    what:'getSubsidia',
                    login:login,
                    password:password,
                    data:newValue,
                    usluga_id: usluga_id
                },
                scope:this
            });
        } else {
            btnGetSubsidiaOshadBank.setDisabled(true);
            btnPrintSubsReestrFromOshadBank.setDisabled(true);
            btnPrintSubsReestrToOshadBank.setDisabled(true);
            btnImportOshadBank.setDisabled(true);
            btnExportOshadBank.setDisabled(true);
            btnImportOplataOshad.setDisabled(true);
            btnImportOplataYkis.setDisabled(true);
            btnSubsidiaOtkat.setDisabled(true);


        }

    }

});
