/*
 * File: app/view/sprav/TabVozvratSubsidiaViewModel.js
 * Date: Thu Jun 01 2017 21:09:40 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ykis.view.sprav.TabVozvratSubsidiaViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.tabvozvratsubsidia'

});