/*
 * File: app/view/sprav/WinAddAktClaimViewModel.js
 * Date: Tue Feb 04 2020 02:55:53 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Ykis.view.sprav.WinAddAktClaimViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.winaddaktclaim'

});